services:

  nestjs:
    build: .
    volumes:
      - .:/home/node/app:z
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    build: ./.docker/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"